class Especie:
    def __init__(self,
                 average_height : str,
                 average_lifespan : str,
                 classification : str,
                 created : str,
                 designation : str,
                 edited : str,
                 eye_colors : str,
                 hair_colors : str,
                 homeworld : str,
                 language : str,
                 name : str,
                 people : list,
                 films : list,
                 skin_colors : str,
                 url : str):
        self.altura_promedio = average_height
        self.esperanza_de_vida_prom = average_lifespan
        self.clasificación = classification
        self.creado = created
        self.designación = designation
        self.editado = edited
        self.colores_ojos = eye_colors
        self.colores_cabello = hair_colors
        self.planeta_origen = homeworld
        self.idioma = language
        self.nombre = name
        self.personas = people
        self.películas = films
        self.colores_piel = skin_colors
        self.url = url